# Section C - Coding **Practice**

Q16. Swap two numbers WITHOUT using a third variable. Implement 3 different methods: (a) using arithmetic, (b) using XOR (^), (c) using tuple unpacking. Compare which is most Pythonic.

In [ ]:
# a) using arithmetic
a=5
b=10
a=a+b
b=a-b
a=a-b
# b) using XOR (`^`)
x=10
y=11
x=x^y
y=x^y
x=x^y
# c) using tuple unpackin
c=20
d=30
c,d=d,c
print(a,b)
print(x,y)
print(c,d)

10 5
11 10
30 20


Q17. Swiggy Order Calculator. Take item price and quantity as input. Compute total = price ×
quantity. Add 18% GST. Add ₹40 delivery charge if total (before delivery) is below ₹500, else delivery
is FREE. Print all components separately and final amount in this format:
Subtotal:
₹450.00
GST (18%):
₹81.00
Delivery:
₹40.00

Total:
₹571.00

In [ ]:
price=float(input("enter a items price:"))
quantity=int(input("enter no.of items :"))
total=price*quantity
gst=total*18/100
if total < 500:
  charges=40.00
else:
  charges=0.00
totaly=total+gst+charges
print(f"total:₹{total:.2f}")
print(f"GST (18%):₹{gst:.2f}")
print(f"Delivery:₹{charges:.2f}")
print("------------------------")
print(f"final amount:₹{totaly:.2f}")

enter a items price:3
enter no.of items :4
total:₹12.00
GST (18%):₹2.16
Delivery:₹40.00
------------------------
final amount:₹54.16


Q18. Temperature converter. Ask user for a value and unit (C or F). Convert and print result rounded
to 2 decimal places. Handle invalid unit input gracefully (print an error message, do NOT crash).

In [ ]:
temp=float(input("enter tempearture:"))
unit=input("enter unit(C or F):")
if unit=="c"  or unit=="C":
  ftemp=(temp*9/5)+32
  print(f"{temp}c is in fornheat {ftemp}f")
elif unit=="f" or unit=="F":
  ctemp=(temp-32)*5/9
  print(f"{temp}f is in celice {ctemp}c")
else:
  print("error invalued option")

enter tempearture:90
enter unit(C or F):F
90.0f is in celice 32.22222222222222c


Q19. Take a 4-digit number as input. Print the sum of its digits – WITHOUT converting it to a string.
(Use only integer arithmetic: //, %.)

In [ ]:
num=int(input("enter a 4 digits number like abcd:"))
n4=num%10
num=num//10
n3=num%10
num=num//10
n2=num%10
num=num//10
n1=num%10
totalsum=n1+n2+n3+n4
print(totalsum)

enter a 4 digits number like abcd:2345
14


Q20. Smart input parser. Take a single input from the user. Detect what type it is – try int first, then
float, else treat as string. Print the value AND its detected type. Example: input "42" → int 42, input
"3.14" → float 3.14, input "hello" → str hello.

In [ ]:
x=input("enter any type of data:")
if x.isdigit():
  print("is integer")
elif x.replace('.','',1).isdigit():
  print("is float")
else:
  print("is str")

enter any type of data:asd
is str


# **C2 – Conditionals & Logic (Q21-Q25)**

Q21. Indian Income Tax Calculator (New Regime, FY 2024–25). Take annual income as input.
Compute tax using these slabs:
Up to ₹3,00,000
: Nil
₹3,00,001 – ₹7,00,000
:
5%
₹7,00,001 – ₹10,00,000 : 10%
₹10,00,001 – ₹12,00,000 : 15%
₹12,00,001 – ₹15,00,000 : 20%
Above ₹15,00,000
: 30%
Tax must be computed slab-wise, NOT flat. Example: income ₹8,00,000 → 0 on first 3L + 5% on next 4L + 10% on
last 1L = ₹20,000 + ₹10,000 = ₹30,000. Print breakdown clearly.

In [ ]:
income=float(input("enter your annual income:"))
tax=0
if income <= 300000:
    print("Slab 1 (Up to ₹3L): Taxable =", income, "| Tax = 0")
else:
    print("Slab 1 (Up to ₹3L): Taxable = 300000 | Tax = 0")
    if income <= 700000:
        taxable = income - 300000
        slab_tax = taxable * 0.05
        tax = tax + slab_tax
        print("Slab 2 (₹3L - ₹7L): Taxable =", taxable, "| Tax =", slab_tax)
    else:
        slab_tax = 400000 * 0.05
        tax = tax + slab_tax
        print("Slab 2 (₹3L - ₹7L): Taxable = 400000 | Tax =", slab_tax)
        if income <= 1000000:
            taxable = income - 700000
            slab_tax = taxable * 0.10
            tax = tax + slab_tax
            print("Slab 3 (₹7L - ₹10L): Taxable =", taxable, "| Tax =", slab_tax)
        else:
            slab_tax = 300000 * 0.10
            tax = tax + slab_tax
            print("Slab 3 (₹7L - ₹10L): Taxable = 300000 | Tax =", slab_tax)
            if income <= 1200000:
                taxable = income - 1000000
                slab_tax = taxable * 0.15
                tax = tax + slab_tax
                print("Slab 4 (₹10L - ₹12L): Taxable =", taxable, "| Tax =", slab_tax)
            else:
                slab_tax = 200000 * 0.15
                tax = tax + slab_tax
                print("Slab 4 (₹10L - ₹12L): Taxable = 200000 | Tax =", slab_tax)
                if income <= 1500000:
                    taxable = income - 1200000
                    slab_tax = taxable * 0.20
                    tax = tax + slab_tax
                    print("Slab 5 (₹12L - ₹15L): Taxable =", taxable, "| Tax =", slab_tax)
                else:
                    slab_tax = 300000 * 0.20
                    tax = tax + slab_tax
                    print("Slab 5 (₹12L - ₹15L): Taxable = 300000 | Tax =", slab_tax)
                    taxable = income - 1500000
                    slab_tax = taxable * 0.30
                    tax = tax + slab_tax
                    print("Slab 6 (Above ₹15L): Taxable =", taxable, "| Tax =", slab_tax)
print("Total Tax to Pay: ₹", tax)


enter your annual income:89999999
Slab 1 (Up to ₹3L): Taxable = 300000 | Tax = 0


Q22. Validate Indian PAN card format WITHOUT using regex. Format: AAAAA9999A, first 5 are
uppercase letters, next 4 are digits, last 1 is an uppercase letter. Total length = 10. Take input and
print "Valid PAN" or "Invalid PAN — <reason>" where reason explains exactly what's wrong.

In [ ]:
pan=input("enter pan card number:")
if len(pan)!=10:
  print("invalied pan number mustbe 10 VALUES")
else:
  letters5=pan[0:5]
  fourdigits=pan[5:9]
  lastletter=pan[9]
  if not letters5.isalpha():
    print("the first five are alphbets")
  elif not letters5.isupper():
    print("the alphabets are must be caps")
  elif not fourdigits.isdigit():
    print("enter valid number of 6 to 9")
  elif not lastletter.isalpha():
    print("the last is might be and an alphabet")
  elif not lastletter.isupper():
    print("the last letter is must be caps")
  else:
    print("valid pan card number")


enter pan card number:OPQWI8129i
the last letter is must be caps


Q23. Bengaluru BESCOM Electricity Bill (LT-2 Residential). Take units consumed as input. Charges:
0 – 50 units
51 – 100 units
101 – 200 units
Above 200 units
: ₹4.10 per unit
: ₹5.55 per unit
: ₹7.10 per unit
: ₹8.15 per unit
Add fixed charge: ₹110. Add 6% government tax on (energy charges + fixed charge). Print itemized bill.

In [ ]:
units = float(input("Enter units: "))
fixedcharge = 110.00
energycharges = 0

print(f"Units: {units}\nfixed: ₹{fixedcharge:.2f}\nslabs:")

slabs = [(50, 4.10, "0-50  "), (50, 5.55, "51-100"), (100, 7.10, "101-200"), (float('inf'), 8.15, ">200  ")]
remaining = units

for limit, rate, label in slabs:
    if remaining <= 0: break
    slab_units = min(remaining, limit)
    cost = slab_units * rate
    energycharges += cost
    remaining -= slab_units
    print(f"  {label} : {slab_units:.1f} units @ ₹{rate} = ₹{cost:.2f}")

subtotal = energycharges + fixedcharge
tax = subtotal * 0.06

print(f"energy total : ₹{energycharges:.2f}")
print(f"subtotal: ₹{subtotal:.2f}\nTax (6%)     : ₹{tax:.2f}")
print(f"TOTAL DUE : ₹{subtotal + tax:.2f}")


Enter units: 90
Units: 90.0
fixed: ₹110.00
slabs:
  0-50   : 50.0 units @ ₹4.1 = ₹205.00
  51-100 : 40.0 units @ ₹5.55 = ₹222.00
energy total : ₹427.00
subtotal: ₹537.00
Tax (6%)     : ₹32.22
TOTAL DUE : ₹569.22


Q24. Cricket Strike Rate Classifier. Take runs scored and balls faced. Compute strike rate =
(runs/balls) × 100. Classify:
SR > 150
→ Explosive (T20 finisher)
100 < SR ≤ 150 → Aggressive (Top order T20)
75 ≤ SR ≤ 100 → Steady (ODI anchor)
SR < 75
→ Defensive (Test match)
Edge case: handle balls = 0 (do not crash, print message instead).

In [ ]:
runs=int(input("enter runs:"))
balls=int(input("enter balls:"))
if balls==0:
  print("balls cant be zero")
else:
  sr=(runs/balls)*100
  if sr>150:
    print("explosive(t20 finisher)")
  elif 100<=sr<=150:
    print("aggressive(top order t20)")
  elif 75<=sr<100:
    print(" Steady (ODI anchor)")
  else:
    print("Defensive (Test match)")

enter runs:89
enter balls:32
explosive(t20 finisher)


Q25. BMI Calculator (Indian standards). Take weight (kg) and height (cm). Compute BMI = weight /
(height_in_meters)². Classify using Indian (not WHO) BMI categories:
BMI < 18.5
18.5 – 22.9
23.0 – 24.9
25.0 – 29.9
BMI ≥ 30
The Unlox Academy
→
→
→
→
→
Underweight
Normal (Indian range — narrower than WHO)
Overweight
Obese Class I
Obese Class II

In [ ]:
weight=float(input("enter weight in kg:"))
heightcm=float(input("enter height in cm:"))
height=heightcm/100
bmi=weight/(height**2)

if bmi <18.5:
  print("Underweight")
elif 18.5 <= bmi <= 22.9:
  print("Normal (Indian range — narrower than WHO)")
elif 23.0 <= bmi <= 24.9:
  print("Overweight")
elif 25.0 <= bmi <= 29.9:
  print("Obese Class I ")
elif bmi >= 30:
  print("Obese Class II")
else:
  print("Invalid BMI")

enter weight in kg:900
enter height in cm:12
Obese Class II


# **C3 – Nested Loop Patterns (Q26-Q30)**

Q26. Print this pattern for N = 5:
1
1 2
1 2 3
1 2 3 4
1 2 3 4 5

In [ ]:
n=5
for i in range(0,n+1):
  for j in range(1,i+1):
    print(j,end=" ")
  print()


1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 


Q27. Print this number diamond for N = 5 (the digits go up to N in the middle row):
1
1 2 1
1 2 3 2 1
1 2 3 4 3 2 1
1 2 3 4 5 4 3 2 1
1 2 3 4 3 2 1
1 2 3 2 1
1 2 1
1

In [ ]:
n=5
for i in range(1,n+1):
  for j in range(1,i+1):
    print(j,end=" ")
  for k in range(i-1,0,-1):
    print(k,end=" ")
  print()
for i in range(n-1,0,-1):
  for j in range(1,i+1):
    print(j,end=" ")
  for k in range(i-1,0,-1):
    print(k,end=" ")
  print()

1 
1 2 1 
1 2 3 2 1 
1 2 3 4 3 2 1 
1 2 3 4 5 4 3 2 1 
1 2 3 4 3 2 1 
1 2 3 2 1 
1 2 1 
1 


Q28. Print a hollow square of size N (only the border is *, inside is blank). For N = 5:
* * * * *
*
*
*
*
*
*
* * * * *

In [ ]:
n=5
for i in range(1,n+1):
  if i==1 or i==n:
    print("* "*n)
  else:
    print("* "+"  "*(n-2)+"*")

* * * * * 
*       *
*       *
*       *
* * * * * 


Q29. Print the first 5 rows of Pascal's Triangle:
1
1 1
1 2 1
1 3 3 1
1 4 6 4 1

In [ ]:
n=5
for i in range(n):
  var=1
  for j in range(i+1):
    print(var,end=" ")
    var=var*(i-j)//(j+1)
  print()

1 
1 1 
1 2 1 
1 3 3 1 
1 4 6 4 1 


Q30. Print this character pattern for N = 5 – letters go up to the N-th alphabet:
A
A B
A B C
A B C D
A B C D E

In [ ]:
n=5
for i in range(1,n+1):
  for j in range(0,i):
    print(chr(65+j),end=" ")
  print()

A 
A B 
A B C 
A B C D 
A B C D E 


# **C4 – Loop Logic (Q31-Q36)**

Q31. Find all Armstrong numbers between 1 and 9999. (An n-digit number is Armstrong if the sum of
its digits each raised to the power n equals the number itself. Example: 153 = 1³ + 5³ + 3³.) Print them
in a clean comma-separated list with a count at the end.

In [ ]:
armstrong=[]
for num in range(1,10000):
  temp=num
  digitscount=0
  while temp>0:
    digitscount+=1
    temp//=10
  temp=num
  digitsum=0
  while temp>0:
    digitsum+=temp%10**digitscount
    temp//=10
  if digitsum==num:
    armstrong.append(num)
print(armstrong)
print(f"count:{len(armstrong)}")

[1, 2, 3, 4, 5, 6, 7, 8, 9]
count:9


Q32. Take N as input. Print the first N terms of the Fibonacci series. Also compute and print the SUM
of those N terms. Do NOT use recursion. Edge case: N = 0 should print nothing, sum = 0. N = 1 should
print just 0.

In [ ]:
N=int(input("enter the number of terms:"))
a=0
b=1
fib=[]
sum=0
for _ in range(N):
  fib.append(str(a))
  sum+=a
  a,b=b,a+b
if N>0:
  print("Fibonacci serices:",",".join(fib))
print("sum of terms",sum)

enter the number of terms:4
Fibonacci serices: 0,1,1,2
sum of terms 4


Q33. Prime check, optimized. Take a number N. Check if it is prime by iterating only up to √N. Then,
print the SUM of all primes between 2 and N (inclusive). Do not use any library.

In [ ]:
n=int(input("enter a number:"))
is_prime=True
if n<2:
  is_prime_n=False
else:
  for i in range(2,n):
    if n%i==0:
      is_prime_n=False
      break
if is_prime_n:
  print(n,"is a prime number")
else:
  print(n,"is not a prime number")
prime_sum=0
for num in range(2,n+1):
  is_prime=True
  for j in range(2,num):
    if num%j==0:
      is_prime=False
      break
  if is_prime:
    prime_sum=prime_sum+num
print("the sum of all prime btw 2 and",n,"is",prime_sum)

enter a number:55
55 is not a prime number
the sum of all prime btw 2 and 55 is 381


Q34. Take a number as input. Reverse it WITHOUT converting to string. Then check if the original and
reversed are equal (palindrome). Handle negative numbers, they should be considered NOT
palindrome (because of the minus sign). Examples: 121 → palindrome, 123 → not palindrome, -121
→ not palindrome.

In [ ]:
num=int(input("enter a number:"))
if num<0:
  print("revered:",num)
  print("negative numbers are not palindrome")
else:
  originalnum=num
  reversed=0
  while num>0:
    lastdigit=num%10
    reversed=(reversed*10)+lastdigit
    num=num//10
  print("reversed",reversed)
  if originalnum==reversed:
    print("its palindrome")
  else:
    print("not a palindrome")

enter a number:45
reversed 54
not a palindrome


Q35. Take two positive integers. Compute their HCF (Highest Common Factor) using Euclidean
algorithm with a `while` loop. Then compute LCM using the relation: HCF × LCM = a × b. Do not use
math.gcd.

In [ ]:
x=int(input("enter a first number"))
y=int(input("enter a seconed number"))
a=x
b=y
while b>0:
  a,b=b,a%b
hcf=a
lcm=(x*y)//hcf
print("the HCF (Highest Common Factor)",hcf)
print("the lcm (lowest common factor)",lcm)

enter a first number55
enter a seconed number45
the HCF (Highest Common Factor) 5
the lcm (lowest common factor) 495


Q36. String scanner, single pass. Take a sentence (e.g., a Swiggy review like "Order came on time,
food was hot, packaging 10/10!"). In ONE pass through the string, count: total characters, total
words, vowels (a, e, i, o, u - case-insensitive), consonants, digits, spaces, and special characters. Print
all counts.

In [ ]:
def scan_review(text):
  total_chars=0
  total_words=0
  vowels=0
  consonants=0
  digits=0
  spaces=0
  special_chars=0
  in_word=False
  vowels_set=set("aeiouAEIOU")
  for char in text:
    total_chars+=1
    if char.isspace():
      spaces+=1
      in_word=False
    elif char.isdigit():
      digits+=1
      in_word=False
    elif char.isalpha():
      if not in_word:
        in_word=True
        total_words+=1
      if char in vowels_set:
        vowels+=1
      else:
        consonants+=1
    else:
      special_chars+=1
      in_word=False
  print("total charecters",total_chars)
  print("total words",total_words)
  print("vowels",vowels)
  print("consonants",consonants)
  print("digits",digits)
  print("spaces",spaces)
  print("special characters",special_chars)
review="Order came on time, food was hot, packaging 10/10!"
scan_review(review)

total charecters 50
total words 8
vowels 14
consonants 20
digits 4
spaces 8
special characters 4


# C5 – Lists, Tuples, Sets, Dicts (Q37-Q42)

Q37. Take 10 student marks (out of 100) as input, space-separated on one line, parse with split() and
map(). Without using sort() or sorted(), find: (a) maximum, (b) minimum, (c) average, (d) count of
students above average, (e) the SECOND highest mark.

In [ ]:
marks=list(map(int,input("enter a 10 students marks separated by spaces:").split()))
total_marks=0
maxs=marks[0]
mins=marks[0]
highest=-1
seconed_highest=-1
for i in marks:
    total_marks=total_marks+i
    if i>maxs:
        maxs=i
    if i<mins:
        mins=i
    if i>highest:
        seconed_highest=highest
        highest=i
    elif i>seconed_highest and i!=highest:
        seconed_highest=i
average=total_marks/len(marks)
above_average=0
for i in marks:
    if i>average:
        above_average+=1
print("maxium marks:",maxs)
print("minumum marks:",mins)
print("average marks:",average)
print("students above average:",above_average)
print("second highest marks:",seconed_highest)

enter a 10 students marks separated by spaces:98 83 39 62 54 42 87 32 84
maxium marks: 98
minumum marks: 32
average marks: 64.55555555555556
students above average: 4
second highest marks: 87


Q38. Word Frequency Analyzer for Swiggy reviews. Take a review sentence. Find the frequency of
each word (case-insensitive, "Food" and "food" should be counted together). Print words sorted by
frequency in descending order. Also print the MOST frequent word and its count. Use a dict.

In [ ]:
import string
review = input("enter a Swiggy review: ")
cleaned_review = review.translate(str.maketrans("", "", string.punctuation)).lower()
words = cleaned_review.split()
word_counts = {}

for word in words:
    if word in word_counts:
        word_counts[word] += 1
    else:
        word_counts[word] = 1

sorted_words = sorted(word_counts.items(), key=lambda item: item[1], reverse=True)
for word, count in sorted_words:
    print(f"'{word}': {count}")

if sorted_words:
    most_frequent_word, highest_count = sorted_words[0]
    print(f"The most frequent word is '{most_frequent_word}' (appears {highest_count} times).")
else:
    print("No words found in the input.")


enter a Swiggy review: food is good and this type of Food i like
'food': 2
'is': 1
'good': 1
'and': 1
'this': 1
'type': 1
'of': 1
'i': 1
'like': 1
The most frequent word is 'food' (appears 2 times).


Q39. Indian States CRUD. Pre-populate a dict with 5 Indian states and their capitals (e.g., Karnataka
→ Bengaluru, Maharashtra → Mumbai). Then build a menu-driven program:
1. Add a new state-capital pair
2. Update an existing capital
3. Delete a state
4. Search a state (return capital, or 'Not found')
5. Display all states sorted alphabetically
6. Exit
Use a while loop. Loop until user chooses option 6.

In [ ]:
states = {
    "Andhra Pradesh": "Amaravati",
    "Telangana": "Hyderabad",
    "Karnataka": "Bengaluru",
    "Maharashtra": "Mumbai",
    "Tamil Nadu": "Chennai",
}
while True:
  print("1. Add a new state-capital pair")
  print("2. Update an existing capital")
  print("3. Delete a state")
  print("4. Search a state (return capital, or 'Not found')")
  print("5. Display all states sorted alphabetically")
  print("6. Exit")
  choice = int(input("Enter your choice: "))
  if choice == 1:
    state = input("Enter the state name: ")
    capital = input("Enter the capital name: ")
    states[state] = capital
  elif choice == 2:
    state = input("Enter the state name: ")
    if state in states:
      capital = input("Enter the new capital name: ")
      states[state] = capital
    else:
      print("State not found")
  elif choice == 3:
    state = input("Enter the state name: ")
    if state in states:
      del states[state]
      print("State deleted")
    else:
      print("State not found")
  elif choice == 4:
    state = input("Enter the state name: ")
    if state in states:
      print("Capital of", state, "is", states[state])
    else:
      print("State not found")
  elif choice == 5:
    sorted_states = sorted(states.items(), key=lambda item: item[0])
    for state, capital in sorted_states:
      print(state, ":", capital)
  elif choice == 6:
    break
  else:
    print("Invalid choice")

1. Add a new state-capital pair
2. Update an existing capital
3. Delete a state
4. Search a state (return capital, or 'Not found')
5. Display all states sorted alphabetically
6. Exit
Enter your choice: 1
Enter the state name: as
Enter the capital name: sd
1. Add a new state-capital pair
2. Update an existing capital
3. Delete a state
4. Search a state (return capital, or 'Not found')
5. Display all states sorted alphabetically
6. Exit
Enter your choice: 5
Andhra Pradesh : Amaravati
Karnataka : Bengaluru
Maharashtra : Mumbai
Tamil Nadu : Chennai
Telangana : Hyderabad
as : sd
1. Add a new state-capital pair
2. Update an existing capital
3. Delete a state
4. Search a state (return capital, or 'Not found')
5. Display all states sorted alphabetically
6. Exit
Enter your choice: 6


Q40. Set Operations. Students in Section A know languages = {Python, Java, C++, SQL}. Students in
Section B know = {Java, JavaScript, Python, Go, SQL}. Using ONLY set operations, find:
(a) Languages known by BOTH sections
(b) Languages known ONLY by Section A
(c) Languages known ONLY by Section B
(d) Total unique languages across both sections
(e) Languages exclusive to one section but not both (symmetric difference)

In [ ]:
section_a = {"Python", "Java", "C++", "SQL"}
section_b = {"Java", "JavaScript", "Python", "Go", "SQL"}
both_sections = section_a.intersection(section_b)
print(" Languages known by BOTH sections ",both_sections)
only_a = section_a.difference(section_b)
print("Languages known ONLY by Section A ",only_a)
only_b = section_b.difference(section_a)
print("Languages known ONLY by Section B",only_b)
total_unique = section_a.union(section_b)
print("Total unique languages across both sections",total_unique)
exclusive = section_a.symmetric_difference(section_b)
print("Languages exclusive to one section but not both (symmetric difference)",exclusive)


 Languages known by BOTH sections  {'SQL', 'Java', 'Python'}
Languages known ONLY by Section A  {'C++'}
Languages known ONLY by Section B {'Go', 'JavaScript'}
Total unique languages across both sections {'C++', 'Go', 'JavaScript', 'Python', 'SQL', 'Java'}
Languages exclusive to one section but not both (symmetric difference) {'C++', 'Go', 'JavaScript'}


Q41. TCS stock prices for a week stored as a tuple: `prices = (3845, 3902, 3878, 3955, 4012, 3998,
4055)` (Mon to Sun in ₹). Find: (a) maximum price and which day, (b) minimum price and which day,
(c) average, (d) biggest single-day gain (and between which days), (e) total volatility = sum of
absolute day-to-day price changes.

In [ ]:
import builtins
max = builtins.max
min = builtins.min
sum = builtins.sum
prices=(3845,3902,3878,3955,4012,3998,4055)
days=["Monday","Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
max_price=max(prices)
max_days=days[prices.index(max_price)]
min_price=min(prices)
min_days=days[prices.index(min_price)]
average=sum(prices)/len(prices)
day_to_day_changes=[]
for i in range(1,len(prices)):
  change = prices[i] - prices[i-1]
  day_to_day_changes.append((change, days[i-1], days[i]))
gains=[item for item in day_to_day_changes if item[0]>0]
biggest_gain,gain_start,gain_end=max(gains,key=lambda x: x[0])
total_volatility=sum(abs(prices[i] - prices[i-1]) for i in range(1, len(prices)))
print(f"(a) Maximum Price: ₹{max_price} on {max_days}")
print(f"(b) Minimum Price: ₹{min_price} on {min_days}")
print(f"(c) Average Price: ₹{average:.2f}")
print(f"(d) Biggest Single-Day Gain: ₹{biggest_gain} (Between {gain_start} and {gain_end})")
print(f"(e) Total Volatility: ₹{total_volatility}")

(a) Maximum Price: ₹4055 on Sunday
(b) Minimum Price: ₹3845 on Monday
(c) Average Price: ₹3949.29
(d) Biggest Single-Day Gain: ₹77 (Between Wednesday and Thursday)
(e) Total Volatility: ₹286


Q42. Given a list of 20 integers (you generate or hardcode them, some duplicates), produce: (a) the
set of unique numbers, (b) the list of numbers appearing more than once, (c) the list of numbers
appearing EXACTLY once. Do this WITHOUT importing Counter or any other library.

In [ ]:
numbers = [12, 5, 8, 12, 19, 5, 23, 42, 8, 11, 7, 19, 5, 14, 88, 23, 90, 3, 11, 14]
unique_numbers = set(numbers)
more_than_once = []
exactly_once = []
for num in unique_numbers:
    count = numbers.count(num)
    if count > 1:
        more_than_once.append(num)
    elif count == 1:
        exactly_once.append(num)
    else:
        print("error")
print("the set of unique numbers:",unique_numbers)
print("the list of numbers appearing more than once:",more_than_once)
print("the list of numbers appearing EXACTLY once:",exactly_once)

the set of unique numbers: {3, 5, 7, 8, 42, 11, 12, 14, 19, 23, 88, 90}
the list of numbers appearing more than once: [5, 8, 11, 12, 14, 19, 23]
the list of numbers appearing EXACTLY once: [3, 7, 42, 88, 90]


# C6 – Strings (Q43-Q45)

Q43. Smart Palindrome Checker. Take a sentence as input. Check if it is a palindrome IGNORING:
case, spaces, and all special characters (punctuation). Examples that should return TRUE: "A man, a
plan, a canal: Panama", "Race car", "No 'x' in Nixon". Hint: build a cleaned version of the string first.

In [ ]:
def palindrome(msg):
  cleaned_char=[char.lower() for char in msg if char.isalnum()]
  cleaned_string="".join(cleaned_char)
  cleaned_string==cleaned_string[::-1]
  is_palindrome=cleaned_string[::-1]
  is_palindrome=cleaned_string

  print("cleaned msg:",cleaned_string)
  print("is palindrome:",is_palindrome)
  return is_palindrome
palindrome("A man, a plan, a canal: Panama")
palindrome("Race car")
palindrome("No 'x' in Nixon")
x=input("enter an sentenc:")
palindrome(x)

cleaned msg: amanaplanacanalpanama
is palindrome: amanaplanacanalpanama
cleaned msg: racecar
is palindrome: racecar
cleaned msg: noxinnixon
is palindrome: noxinnixon


KeyboardInterrupt: Interrupted by user

Q44. Manual Title Case. Take a sentence (e.g., "hello world from bengaluru"). Capitalize the first
letter of EACH word, but do NOT use .title() or .capitalize(). Use only .upper() / .lower() and string
indexing. Output: "Hello World From Bengaluru".

In [ ]:
def manual_title_case(sentence):
    words = sentence.split(" ")
    title_words = []

    for word in words:
        if word:
            first_letter = word[0].upper()
            remaining_letters = word[1:].lower()
            processed_word = first_letter + remaining_letters
            title_words.append(processed_word)
        else:
            title_words.append("")
    return " ".join(title_words)
input_text = "hello world from bengaluru"
output_text = manual_title_case(input_text)

print(f"Output:{output_text}")

Output:Hello World From Bengaluru


Q45. Caesar Cipher Encryptor. Take a message and a shift value N as input. Encrypt by shifting each
letter forward by N positions in the alphabet (wrapping around, Z + 1 = A). Preserve case. Keep digits,
spaces, and special characters UNCHANGED. Example: "Hello, India!" with shift 3 → "Khoor, Lqgld!"

In [ ]:
def caesar_cipher(message, shift):
    encrypted_chars = []

    for char in message:
        if char.isupper():
          shifted_char = chr((ord(char) - 65 + shift) % 26 + 65)
          encrypted_chars.append(shifted_char)
        elif char.islower():
          shifted_char = chr((ord(char) - 97 + shift) % 26 + 97)
          encrypted_chars.append(shifted_char)
        else:
           encrypted_chars.append(char)

    return "".join(encrypted_chars)

given_text = "Hello, India!"
shift_value = 3
output = caesar_cipher(given_text, shift_value)

print(f"Shift Value: {shift_value}")
print(f"Encrypted text: {output}")

Shift Value: 3
Encrypted text: Khoor, Lqgld!


# C7 – Functions (Q46-Q47)

Q46. Write a function `calculate_gst(amount, gst_rate=18, gst_inclusive=False)`:
- If gst_inclusive=False: amount is base, add GST on top
- If gst_inclusive=True: amount already includes GST, extract it
- Return a tuple: (base_amount, gst_amount, total_amount)
- All values rounded to 2 decimals
Test cases:
calculate_gst(1000)
→ (1000.00, 180.00, 1180.00)
calculate_gst(1180, gst_inclusive=True) → (1000.00, 180.00, 1180.00)
calculate_gst(500, gst_rate=5)
→ (500.00, 25.00, 525.00)

In [ ]:
def calculate_gst(amount, gst_rate=18, gst_inclusive=False):
    if gst_inclusive:
      total_amount=amount
      base_amount = total_amount/(1+(gst_rate/100))
      gst_amount = total_amount-base_amount
    else:
        base_amount=amount
        gst_amount = amount*(gst_rate/100)
    total_amount = base_amount + gst_amount
    return round(base_amount, 2), round(gst_amount, 2), round(total_amount, 2)

print(calculate_gst(1000))
print(calculate_gst(1180, gst_inclusive=True))
print(calculate_gst(500, gst_rate=5))
print(calculate_gst(1000, gst_rate=5, gst_inclusive=True))

(1000, 180.0, 1180.0)
(1000.0, 180.0, 1180.0)
(500, 25.0, 525.0)
(952.38, 47.62, 1000.0)


Q47. Write a RECURSIVE function `power(base, exp)` that computes base raised to exp, WITHOUT
using the `**` operator and WITHOUT using `pow()`. Handle exp = 0 (return 1) and negative exp
(return 1/power(base, -exp)). Test with: power(2, 10), power(5, 0), power(3, -2).

In [ ]:
def power(base, exp):
    if exp==0:
        return 1
    elif exp < 0:
        return 1/power(base, -exp)
    else:
      return base*power(base, exp-1)

print(power(2, 10))
print(power(5, 0))
print(power(3, -2))

1024
1
0.1111111111111111


# \C8 – NumPy Foundations (Q48-Q50)

Q48. Identity Matrix Manipulations. Using NumPy: (a) create a 5×5 identity matrix using np.eye(), (b)
multiply every element by 10, (c) transpose it (yes, it looks the same, explain in a comment WHY
transpose of an identity is itself), (d) compute the sum of diagonal elements, (e) compute the sum of
all elements. Print each step.

In [ ]:
import numpy as np
idenity_matrix=np.eye(5)
print("the identity matrix is:")
print(idenity_matrix)
scaled_matrix=idenity_matrix*10
print("the scaled matrix is:")
print(scaled_matrix)
transposed_matrix=scaled_matrix.T
print("the transposed matrix is:")
print(transposed_matrix)
sum_diagonal=np.diag(transposed_matrix).sum()
print("the sum of diagonal elements is:")
print(sum_diagonal)
# the tranceposed matrix is sames as scaled matrix becase the diagonal elements are the same numbers but the non-diagonal elements are zero so, we trancesposes we cant find the differnces btw them

the identity matrix is:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
the scaled matrix is:
[[10.  0.  0.  0.  0.]
 [ 0. 10.  0.  0.  0.]
 [ 0.  0. 10.  0.  0.]
 [ 0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0. 10.]]
the transposed matrix is:
[[10.  0.  0.  0.  0.]
 [ 0. 10.  0.  0.  0.]
 [ 0.  0. 10.  0.  0.]
 [ 0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0. 10.]]
the sum of diagonal elements is:
50.0


Q49. Zomato Weekly Sales Analytics. Create a NumPy array of 7-day Zomato Bengaluru sales (in ₹):
sales = np.array([12000, 18500, 14200, 22100, 19800, 35200, 28400])
# Mon
Tue
Wed
Thu
Fri
Sat
Sun
Without using loops, compute and print:
(a) Total weekly sales
(b) Daily average
(c) The day (Mon/Tue/...) with maximum sales
(d) Number of days with sales above the weekly average
(e) Percentage growth from Monday to Sunday
(f) An array of day-on-day % changes (length 6)

In [ ]:
import numpy as np
sales=np.array([12000,18500,14200,22100,19800,35200,28400])
days=np.array(["Mon","Tue","Wed","Thu","Fri","Sat","Sun"])
total_sales=sales.sum()
print("the total weekly sales is:")
print(total_sales)
max_sales=sales.max()
print("the maximum weekly sales is:")
print(max_sales)
min_sales=sales.min()
print("the minimum weekly sales is:",min_sales)
average_sales=sales.mean()
print("the average weekly sales is:",average_sales)
above_average=np.count_nonzero(sales>average_sales)
print("the number of days with sales above the weekly average is:",above_average)
#persentage of grouth of monday to sunday
percentage_growth=(sales[-1]-sales[0])/sales[0]*100
print("the percentage growth from monday to sunday is:",percentage_growth)
lastday_sales=sales[:-1]
today_sales=sales[1:]
day_onpercentage=(today_sales-lastday_sales)/lastday_sales*100
print("the day-on-day percentage change is:",day_onpercentage)

the total weekly sales is:
150200
the maximum weekly sales is:
35200
the minimum weekly sales is: 12000
the average weekly sales is: 21457.14285714286
the number of days with sales above the weekly average is: 3
the percentage growth from monday to sunday is: 136.66666666666666
the day-on-day percentage change is: [ 54.16666667 -23.24324324  55.63380282 -10.40723982  77.77777778
 -19.31818182]


Q50. The Border Pattern Challenge – NO explicit loops. Create a 5×5 NumPy array where the BORDER
is 1 and the INTERIOR is 0. Output should look like:
[[1 1 1 1 1]
[1 0 0 0 1]
[1 0 0 0 1]
[1 0 0 0 1]
[1 1 1 1 1]]
Constraint: You may use np.ones(), np.zeros(), and slicing, but NO `for`, NO `while`, NO list comprehension. Only
NumPy operations.

In [ ]:
import numpy as np
array=np.ones((5,5))
array[1:-1,1:-1]=0
print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
